# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-started-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: get-started-node
  template:
    metadata:
      labels:
        app: get-started-node
    spec:
      containers:
      - name: get-started-node
        image: myapp:v1.0.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: get-started-service
  labels:
    app: get-started-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: get-started-node
